variables:
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/juanwolf/ces2015:latest
    CONTAINER_TAGGED_IMAGE : registry.gitlab.com/juanwolf/ces2015:$CI_BUILD_TAG

stages:
    - release

release:
    stage: release
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t $CONTAINER_TAGGED_IMAGE .
        - docker tag $CONTAINER_TAGGED_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
    only:
        - tags
    tags:
        - production

