variables:
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/juanwolf/juanwolfs-blog:latest
    CONTAINER_TAGGED_IMAGE : registry.gitlab.com/juanwolf/juanwolfs-blog:$CI_BUILD_TAG

stages:
    - release

release:
    stage: release
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build --pull -t $CONTAINER_TEST_IMAGE .
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_TAGGED_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
    tags:
        - production

